### ISSUE TITLE
Encoding on subtitles

### ISSUE THREAD

**Issue by mtwww** [PopcornTimeTV/PopcornTimeTV#116]
With the new version 0.6.3 subtitles works great.
But for subtitles we are having character problems. For example Turkish Subtitles doesn't seems correct.
I hope it can be fixed easily without doing a lot work.

**Comment by mtwww** [comment]
there is also a selecting issue between tags on subtitles.
i attached screenshot

![img_6977](https://cloud.githubusercontent.com/assets/19256012/15393344/73126206-1dd5-11e6-81a5-7750fdb631ef.JPG)

**Comment by Evhelden** [comment]
Indeed this issue with <i> and </i> shows in Dutch sometimes as  well.

**Comment by tomto147** [comment]
Same problems with Polish ones if they are rarely available on Opensubtitles ;-) But I think its not the problem of this app but source files with subtitles itself. On the other hand I was fixing same problem w Squire app (similar to Popcorn). And we were able to fix Polish encoding together with the developer of the app.

**Comment by Evhelden** [comment]
Nope. Same for Dutch subtitles. Seems related to the app.

**Comment by tomto147** [comment]
I think its not related to the app as at least in Polish version some subtitles are encoded properly and some not. There fore I think it might be related to source files with subtitles to different movies. Polish character set is not "normal", a lot of letters with points, lines etc. like in German.

**Comment by buzzel** [comment]
What are the <i></i> tags used for in this case? Can I just strip them from the strings or are they needed in languages? I've never done anything like this trying to figure out how things are supposed to work.

**Comment by joaomvfsantos** [comment]
That's the HTML tag for italic text. Striping it out has no side effects other than not showing this particular part of text in italic. Would be good to display it correctly but I think we can live with it especially if the effort to fix it is too high, imo.

**Comment by mtwww** [comment]
about encoding, i think need to have a look official popcorntime desktop version.. to understand how they sort it out..

i don't think that opensubtitles files encoded in wrong.. because when i download any Turkish subtitle from there and use it with any DLNA or soft video player it works perfect if i choose Turkish as coding..

i think must add something like encoding convertor by chosen subtitle language...

**Comment by buzzel** [comment]
The thing with the PopcornTime Desktop version is it's written in Node JS I believe. A lot of things wont translate to Swift/Obj-C. I've added some more checks for subtitle parsing so hopefully that works. 

@joaomvfsantos I have an idea regarding the formatting so going to see if I can get that to work. If not, I'll just strip that stuff.

**Comment by tomto147** [comment]
@buzzel 
I am still seeing this {i} markers (and other) after the strip
And still no proper encoding of letters :-(

**Comment by buzzel** [comment]
@tomto147 Did you pull the changes from the master branch?

**Comment by tomto147** [comment]
Yes. First I tried to use python scrip, and it updated 3 files as I remember. But to be 100% sure I have pulled all of the with git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git.
BTW, after pulling from master branch my changes to subtile size have been changed back to 15, 30, 48.

**Comment by buzzel** [comment]
@tomto147 Any chance you could hop on Slack? Be easier if I could push a couple of things and get you to test them.

**Comment by buzzel** [comment]
@tomto147 Ok, give what I just pushed a whirl. Also, there is the new swift script you can try out. `swift install.swift` to run it

**Comment by tomto147** [comment]
@buzzel 
1. Swift install script works just fine. Just tested it.
2. I have pulled all the files from the master
3. I can still see all of the markers in subtitles like {i} / etc.
4. Still wrong encoding of characters in Polish subtitles.
5. Example - Avengers Age of Ultron is **encoding properly** in Polish but with lots of {i} / in the begging of lines
6. Example - StarWars episode VII is **encoding wrong** and with lots of {i} / 
7. Yes I can join Slack. My company is using it every day but for me it was "unfriendly" UX. Or I am to old to get to it ;-))) Just give me the slack group name and email or whatever is needed to get to your channel. I will test for you.

**Comment by puba** [comment]
Same issue here with Slovenian subtitles, seems like characters like š,č, ž are not encoded right...also those <i> tags are really annoying. 
Everything else works just fine.

**Comment by buzzel** [comment]
@tomto147 I have tested it and don't seem to see those tags in subtitles. Can you send me a screenshot of the tags? I'm wondering if some subtitles are using something other than <i> <u> or <b>. I have checked the strings and they are indeed pulled from the there. Also, try removing the cache in the app. If you open up the settings in PopcornTime there is an option to remove the cache. I'm wondering if there are any broken subtitles left in there.

**Comment by tomto147** [comment]
I have cleared cash and still no go...
Look at the screenshot below. < i > , and every upper index number, and question mark upside down is wrong encoding. Once again maybe you can inspect this particular movie and its Polish subtitles file (StarWars episode VII, where the encoding is wrong + this unnecessary <i>). And then compare it with Avengers and its Polish subtitles files where encoding is ok but still < i > are present. I think to reproduce this at your space maybe you would have to change appleTV to Polish? Or at least choose Polish subtitles in this two movies.

![simulator screen shot 21 05 2016 10 49 14](https://cloud.githubusercontent.com/assets/19311926/15447414/0dd3f008-1f42-11e6-8082-445ce8f33d9e.png)

**Comment by aggelos81** [comment]
I had the same issue with Greek subtitles so I opened a file from the subtitles that the movie was downloading with Coda where I found the correct encoding for the file, it was ISO8859-7 which is supported using the cfencoding kCFStringEncodingISOLatinGreek. But the NSString class could not use this encoding to decrypt the file so I fed the data from the subtitle file into an NSData item and from there passed it to a cfstringref item with the cf creator CFStringCreateWithBytes. This decoded the string correctly and then used a bridge to place the cfstring into the nsstring data.

`NSData* dataFile = [NSData dataWithContentsOfFile:lastSelected[@"path"]];`

`CFStringRef cfstring = CFStringCreateWithBytes(kCFAllocatorDefault, dataFile.bytes, dataFile.length, kCFStringEncodingISOLatinGreek, YES);
CFRelease(cfstring);`

**Comment by tomto147** [comment]
I am to weak in coding to reproduce your workaround ;-) Just know that Polish encoding should be done using ISO8859-2 or UTF-8. Can you help? ;-)

**Comment by aggelos81** [comment]
I believe that it should be good now

<img width="1440" alt="screen shot 2016-05-21 at 15 35 50" src="https://cloud.githubusercontent.com/assets/660807/15448408/c55e3fa4-1f69-11e6-8853-1b1cfa8476af.png">

**Comment by RefusedFlow** [comment]
You're more than welcome to submit PR's 😄

**Comment by aggelos81** [comment]
Done... PR #126

**Comment by mtwww** [comment]
hope the author pull that within all common languages fix in that way.

**Comment by tomto147** [comment]
@aggelos81 
Thanks for your support ;-) Sill one character is wrong at this screen. It should be "tajną" not as it is. Which means the encoding i probably still wrong. How can I test it with your commit? Don't now how to update it locally ;-(

@buzzel 
And I am sure buzzer will try to figure out how to solve it and pull for the master branch

**Comment by ozkrtech** [comment]
I found this out on "The Martian" movie and some others while using "spanish" subtitles.

<i> and </i>

[image1.JPG]

Oscar Rodriguez
IT Technician

On May 21, 2016, at 11:05 AM, tomto147 <notifications@github.com<mailto:notifications@github.com>> wrote:


@aggelos81<https://github.com/aggelos81>
Thanks for your support ;-) Sill one character is wrong at this screen. It should be "tajn?" not as it is. Which means the encoding i probably still wrong. How can I test it with your commit? Don't now how to update it locally ;-(

@buzzel<https://github.com/buzzel>
And I am sure buzzer will try to figure out how to solve it and pull for the master branch

-

**Comment by aggelos81** [comment]
What you can do is go to my fork of the project which you can find next to my name on your reply and download my project of the popcorntimetv which will have the required changes. you will also need to follow the same instructions to build the project as you did with the original project

**Comment by tomto147** [comment]
@aggelos81 
I have downloaded the project from repository, but when looking inside the changed files the changes were not there. I have done it once more, installed everything any still no Polish encoding

**Comment by aggelos81** [comment]
Did you enter the command git checkout 0.6.3? If so then please delete and
redownload the project.

**Comment by mtwww** [comment]
adding 

        if([name isEqualToString:@"Turkish"]){
            NSData* dataFile = [NSData dataWithContentsOfFile:path];
            CFStringRef cfstring = CFStringCreateWithBytes(kCFAllocatorDefault, dataFile.bytes, dataFile.length, kCFStringEncodingISOLatin5, YES);
            string = (__bridge NSString *)cfstring;
            CFRelease(cfstring);
        }

fix also Turkish subtitles..  @aggelos81 you might be add this into your pull request ?

**Comment by tomto147** [comment]
@aggelos81 
Yes I did use install.swift... I don't get you... Shall I delete all and redownload from your repo and what next? Do everything aparat from cheking out 0.6.3?

**Comment by aggelos81** [comment]
Exactly!

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.12.25&pv=9.3.2&source=email_footer_2]
On Sat, May 21, 2016 at 9:55 PM, tomto147 <notifications@github.com> wrote:
@aggelos81 [https://github.com/aggelos81]
Yes I did use install.swift... I don't get you... Shall I delete all and redownload from your repo and what next? Do everything aparat from cheking out 0.6.3?

**Comment by tomto147** [comment]
@aggelos81 
OK I've succeeded. Thanks a lot! Polish subtitles do work now. 

But.... still one letter from Polish is missing don't know why this one but it is used pretty often. Take a look here 
https://en.wikipedia.org/wiki/ISO/IEC_8859-2 
it's in the table where column "_1" and row "A_" and "B_" cross. It is not being encoded properly - only this one letter.

Second thing. I have noticed another unnecessary HTML markings like this {y:i}
![simulator screen shot 22 05 2016 09 22 00](https://cloud.githubusercontent.com/assets/19311926/15452960/5732e852-2001-11e6-8c65-defc52a2ddcc.png)

So I have added the line to the SRT parser:
newString = [newString stringByReplacingOccurrencesOfString:@"{y:i}" withString:@""];

but it is not being recognised...

**Comment by aggelos81** [comment]
@mtwww I have added the turkish encoding to the pull

**Comment by buzzel** [comment]
@tomto147 @mtwww @aggelos81 Some subtitle fixes and support for TV shows were pushed to the master branch. Feel free to give it a go and see how it works.

**Comment by mtwww** [comment]
hi @buzzel . you just push some changes right ? didn't update the version ?

**Comment by buzzel** [comment]
@mtwww Correct, just pushed them to the master branch. Once I know the subtitle stuff actually works i'll release a new version.

**Comment by mtwww** [comment]
for example for which tv show ? i tried with Game of Thrones last season, there is no subtitle..

**Comment by buzzel** [comment]
Honestly, its trial and error. Some shows have them or return results and some don't. The biggest thing I am worried about is the encoding. Can you test it out on movies?

**Comment by mtwww** [comment]
@buzzel not good news.. when @aggelos81 fixed the subtitles it was working good.
now i deleted and did a new clone, new installation its same like before.. subtitles and encoding doesn't work well..

![viber image](https://cloud.githubusercontent.com/assets/19256012/15586114/5cc31372-238b-11e6-8cd4-b52270d237ad.jpg)

![viber image2](https://cloud.githubusercontent.com/assets/19256012/15586120/601f5ad0-238b-11e6-99a8-6d133378cec6.jpg)

**Comment by buzzel** [comment]
@mtwww Run a build and Clean for me, also, in terminal run `git log -1 --pretty=%B` and tell me what it shows

**Comment by mtwww** [comment]
@buzzel this is turkish.

First screenshot : must be without tags and exactly ''Merkezi bir bina birtür enerji kalkanıyla korunuyor. ''
Second screenshot : - Lanet olsun!  - Ladına dikkat et !  

Its latin5 encoding. i did already did a fresh clone.
here is the output of your question :
Update the readme for the new script

**Comment by buzzel** [comment]
That is an old version. Run this. 
`git checkout master` then `git pull`

**Comment by mtwww** [comment]
i am in PopcornTimeTV folder ;

$git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	PopcornTime.xcodeproj/project.pbxproj
Please, commit your changes or stash them before you can switch branches.
Aborting

$ git pull
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/PopcornTimeTV/PopcornTimeTV
   b689655..4e9fe11  master     -> origin/master
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

am i missing something ?

**Comment by buzzel** [comment]
Run this entire command and it should fix this issue.

`git stash && git checkout master && git pull && git stash pop`

Copy and paste that whole line and that should fix it

**Comment by mtwww** [comment]
:) this time works yes , but for Avengers, i choose turkish.. one subtitle loaded.. encoding wrong again..
but this subtitle definitely not Avenger's subtitle :) it belongs to some other movie.. 

![viber image423](https://cloud.githubusercontent.com/assets/19256012/15587361/881801da-2391-11e6-9673-4c22fa6517b3.jpg)

tv series, i tried with game of thrones, now i can see all subtitles.. and at the beginning of the show --opensubtitles-- advertisement (even if i don't choose subtitle).

![7668](https://cloud.githubusercontent.com/assets/19256012/15587501/29ba9584-2392-11e6-92a5-cef8721b63aa.jpg)

it seems that subtitles working with Encoding problems... and choosing right subtitles problems too..

**Comment by buzzel** [comment]
I have no idea how things are supposed to show so encoding is completely wrong still and it downloading the wrong subtitles?

**Comment by mtwww** [comment]
encoding must be latin5 for turkish.
and movies yes.. wrong subtitles.. tv shows seems fine

**Comment by buzzel** [comment]
@mtwww Is this formatted correctly? 
<img width="2032" alt="screen shot 2016-05-26 at 1 17 35 pm" src="https://cloud.githubusercontent.com/assets/17832027/15588756/41ec26ca-2344-11e6-9c61-005abc74dba2.png">

**Comment by buzzel** [comment]
I pushed some more changes so run  `git stash && git pull && git stash pop`

**Comment by mtwww** [comment]
I am going to do now,
It must be like : 
- Saldırı emrini kim verdi size ? 
- Sayın Strucker, saldıranlar İntikamcılar.

in @aggelos81 's solution, just pushing encoding in latin5 was fixed the issue.

**Comment by buzzel** [comment]
Oh so none of the hyphens or anything

**Comment by mtwww** [comment]
now correct subtitles ! its ok..
Öö,Üü are ok but capital i and small ı still has problems..  i didn't able to check ğĞ Çç ..

**Comment by aggelos81** [comment]
```
if (e) {
        NSStringEncoding encoding = CFStringConvertEncodingToNSStringEncoding(e);
        NSString *string = [NSString stringWithContentsOfFile:path encoding:encoding error:&error];
        return string;
```
you should change this check into the below since the universal detector does not return nil cfstringencoding if it cannot find the correct encoding but the following variable!!
```
if (e!=kCFStringEncodingInvalidId) {
        NSStringEncoding encoding = CFStringConvertEncodingToNSStringEncoding(e);
        NSString *string = [NSString stringWithContentsOfFile:path encoding:encoding error:&error];
        return string;
```

**Comment by buzzel** [comment]
@mtwww Just pushed something to test. I'm not seeing any of the hyphens and such as I was before so have a go with it. 

@aggelos81 Yeah, I released that a few commits ago but since the UniversalDetector isn't working im going to remove it.

**Comment by buzzel** [comment]
0.6.4 was pushed. If these issues still persist reopen a new issue as this one is clogged up! :)
