### ISSUE TITLE
TV shows subtitles

### ISSUE THREAD

**Issue by guiwunsch** [PopcornTimeTV/PopcornTimeTV#180]
Hi.
There isn't avaiable any subtitles in Tv shows. I've just try Arrow, GoT and Blindspot and doesnt works for me. The movies subtitles works good. Is there a bug in this function?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Imdb id needs to be fetched for episodes. TVDB id (used atm) will not work

**Comment by FlaviaBondJamesBondsHusband** [comment]
should be fixed in latest commit

**Comment by gragera** [comment]
I tried some of them and have no subs for it (Westworld for example). In the iOS version I have seen that trakt.tv API does not always returns imdb ids for every episode, making the subtitle fetch to fail. Might this be the case for Apple TV as well?

**Comment by moh0sw** [comment]
@gragera @FlaviaBondJamesBondsHusband yep same here
the subtitles for TV Shows still not working
