### ISSUE TITLE
Unable to login with Open Subtitles

### ISSUE THREAD

**Issue by tomeranaray** [PopcornTimeTV/PopcornTimeTV#182]
Hi, I'm not sure if this is a bug but in the latest version I cannot login with my credentials for OpenSubtitles.org. I always get the error that the credentials are incorrect. 

Is this a known issue or do I need a login from another website?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@tomeranaray it appears the API was down for a short while and was returning 403 for all requests. Should be fixed now

**Comment by mtwww** [comment]
i see its long time ago but same problem still exist ? 
i just installed as new installation today and getting wrong user/pass error..
