### ISSUE TITLE
AudioViewController not working (rewrite)

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#289]
- [ ] Redo audio discovery with `AVSpeakerManager`
- [ ] Actually implement "Full Dynamic Range" and "Reduce Loud Sounds"
- [ ] Fetch images for speakers
- [ ] Fix focusing

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master

**Comment by MatthieuTnsc** [comment]
Apple TV - commit: 6dad8ebb86f5b66ee0eb63443ec754490ec5cf94
Still having the following issue: **Audio delay with AirPlay speaker**

Behaviour:
1. Launch a movie
2. Swipe down and select "audio"
3. Select an AirPlay speaker listed in the AudioViewController (instead of "Apple TV" by default)
4. Audio and video are out of sync and impossible to match them with manual delay

For information, most of other application automatically sync audio and video when AirPlay speaker is selected (I'm quite sure the SDK offer a native feature to handle this, but impossible to find it yet).
