### ISSUE TITLE
Crashes on launch iOS 10.2 iphone 6

### ISSUE THREAD

**Issue by xSYDx** [PopcornTimeTV/PopcornTimeTV#343]
Crashes on launch every time

**Comment by FlaviaBondJamesBondsHusband** [comment]
When did you install the app. I presume you are aware that free provisioning profiles expire every 7 days

**Comment by brynts** [comment]
popcorntime crash on 10.2, installed from cydia/repo popcorntimetv.github.io

**Comment by xSYDx** [comment]
I installed from the popcorntime repo (here) and I compiled my own .deb of it and uploaded it to my repo to try to see if that would have maybe fixed it... It crashes on launch when installing from this github repo and when I put it up on my repo

**Comment by FlaviaBondJamesBondsHusband** [comment]
@xSYDx @brynts I have pushed an update to the cydia repo hopefully fixing the crashes. Unfortunately i am unable to debug the changes any further as the iOS 10 jailbreak is failing on my iPad. App Sync Unified from the repo: https://cydia.angelxwind.net is required for the app to work but has yet to be updated for iOS 10 and installing it on your device will result in a bootloop. Until this is fixed the app will probably crash on startup, but, as I say, I am unable to test any further so I do apologies.

**Comment by technosid77** [comment]
It works perfectly fine on my ios 10.2.1 on iphone 6s

**Comment by brynts** [comment]
@technosid77 are you install Coolstar's Stashing? because it's still crashed on me
