### ISSUE TITLE
pt-br

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#466]
Translated to PT

https://gist.github.com/CavalcanteLeo/7f4ab39a20cb967874faf384a9dada77

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks so much for all your hard work. It's much appreciated 😄 . PT-BR translations have been added to the latest master build and will be in the next release - 3.1.3 - whenever that is.

**Comment by CavalcanteLeo** [comment]
Some UIButtons doesn't fit on apple TV in pt, like "sort" button

**Comment by CavalcanteLeo** [comment]
also in iPhone , on movies information, at the bottom:

![img_3091](https://cloud.githubusercontent.com/assets/1735944/25759056/52e73fe2-31a7-11e7-965c-6e368fab2271.PNG)

have a look at "Lançamento"

**Comment by FlaviaBondJamesBondsHusband** [comment]
Will take a look at these now

**Comment by FlaviaBondJamesBondsHusband** [comment]
Ok I think everything should be fixed in master. Wanna give it a go?

**Comment by CavalcanteLeo** [comment]
Fixed!

**Comment by CavalcanteLeo** [comment]
I have changed the file with some translates issues.

The links still the same
https://gist.github.com/CavalcanteLeo/7f4ab39a20cb967874faf384a9dada77

**Comment by FlaviaBondJamesBondsHusband** [comment]
Updated translations in master. Can you test to see if they're OK?

**Comment by CavalcanteLeo** [comment]
Everything is well translated, but there is an item, that didn't translate, even with my file is correct:

My gist:
https://gist.github.com/CavalcanteLeo/7f4ab39a20cb967874faf384a9dada77#file-pt-v1-1-xliff-L1060

PopcornTimeTV:
https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/PopcornTime/pt-BR.lproj/Localizable.strings#L428

where
`Legendas para surdos e Hard of Hearing (SDH) referem-se a legendas na versão original com a adição de informações relevantes não-diálogo `



should be
`Legendas para surdos e pessoas com dificuldade de audição (SDH) referem-se a legendas na versão original com a adição de informações relevantes não-diálogo `

*e pessoas com dificuldade de audição* instead of *Hard of Hearing* 

@FlaviaBondJamesBondsHusband 
why didn't it change?

Does it need to be reopened?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We're getting ready for the next release and were wondering if you wouldn't mind updating your 
[Localisations](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1128084/Updates.zip). The release is scheduled for next week so please have it completed for then. Thanks!

**Comment by CavalcanteLeo** [comment]
K, I'll translate tomorrow

**Comment by CavalcanteLeo** [comment]
done, same URL

https://gist.github.com/CavalcanteLeo/7f4ab39a20cb967874faf384a9dada77

**Comment by CavalcanteLeo** [comment]
done, same URL

https://gist.github.com/CavalcanteLeo/7f4ab39a20cb967874faf384a9dada77

**Comment by FlaviaBondJamesBondsHusband** [comment]
@CavalcanteLeo That's perfect. There's just three more that were added to PopcornTorrent if you wouldn't mind translating them too: https://github.com/PopcornTimeTV/PopcornTorrent/blob/master/PopcornTorrent/Supporting%20Files/Base.xliff

**Comment by CavalcanteLeo** [comment]
done:

https://gist.github.com/CavalcanteLeo/9ed46e4d776331bc5ec119f8655cbfb4

**Comment by CavalcanteLeo** [comment]
Also, there is a layout bug, on the accessibility  description.

Follow the full text: 
`Legendas para surdos e pessoas com dificuldade de audição (SDH) referem-se a legendas na versão original com a adição de informações relevantes não-diálogo `

and see how it fits on the screen:
![img_3982](https://user-images.githubusercontent.com/1735944/27929551-c930eee4-6269-11e7-8473-f618bcaa60b5.PNG)

**Comment by FlaviaBondJamesBondsHusband** [comment]
> Also, there is a layout bug, on the accessibility description.

We will investigate this further. It is not limited to Portugese

> And genre type wasn't translated:

Genres pulled from the API do not get translated.

Thanks for all your hard work translating :).
