### ISSUE TITLE
crash on settings tab

### ISSUE THREAD

**Issue by sasagr** [PopcornTimeTV/PopcornTimeTV#55]
Build it from scratch and when I select the setting tabe on the simulator (I did not tried it yet on the physical box) it crashes and I get the following message as per attachment.
![snap](https://cloud.githubusercontent.com/assets/3427877/18160344/b6f91d36-7035-11e6-8304-2c9e02566860.png)

**Comment by popcornMaster** [comment]
I have not been able to reproduce this issue! Please delete the project from your computer and re-download and try again, it should resolve itself!

**Comment by sasagr** [comment]
I already did the following a couple of times and the issue is still there. I have no idea what else I could do.

I cleared out the DerivedData
~/Library/Developer/Xcode/DerivedData

I manually...
sudo gem cleanup cocoapods
sudo gem uninstall cocoa pods
sudo gem install cocoa pods

also
rm -rf /Pods && rm -rf Podfile.lock &&rm -rf ~/.cocoapods/repos/popcorntimetv

and also deleted the entire PopcornTimeTV folder and cloned it again.

I still get the same error and only when I click the settings tab

Pls advise if any other suggestions

**Comment by popcornMaster** [comment]
Please run a search inside xcode for "encodingtypes" using the button highlighted below on the left panel. If it comes does not come up with the file encodingTypes.plist, then please add it from the folder PopcornTime/encodingTypes.plist. If it does come up there is nothing wrong with the files and I really cannot help!

<img width="260" alt="screen shot 2016-09-03 at 12 56 23" src="https://cloud.githubusercontent.com/assets/20759040/18224208/d4acb5d4-71d6-11e6-91e0-0b89f5887a6d.png">

**Comment by sasagr** [comment]
the file was already there. I m trying to clean/remove everything again and make a scratch new installation and suddenly I get now this message after I launch the script

Updating spec repo `popcornmaster`
  $ /usr/bin/git pull --ff-only
Username for 'https://github.com': 

and it is there like waiting for my input

???

**Comment by popcornMaster** [comment]
just press return/enter on both the username and password prompts!

**Comment by sasagr** [comment]
after pressing enter nothing happens. it just changes line and it stays there forever...

**Comment by popcornMaster** [comment]
pod repo remove master
pod setup
pod install

Please try running these!

**Comment by sasagr** [comment]
I managed to build it using above instructions but the initial issue is still there when I try to select settings tab. 
![untitled](https://cloud.githubusercontent.com/assets/3427877/18227054/5d88dd7a-7221-11e6-94e9-20a2b8814377.png)

**Comment by popcornMaster** [comment]
There really is nothing I can do for you! Please try selecting reset content and settings on the sim, if this does not work either then try just installing the app on your device! It will work!

**Comment by sasagr** [comment]
the reset solved the issue at least on the simulator.
Unfortunately I already tried to the on app on the device yesterday and I was getting the same issue. I will try to install it now to the device, eventually I will have to consider a reset also on my device
