### ISSUE TITLE
Subtitle in the new version (3.2.30)

### ISSUE THREAD

**Issue by Red-Mak** [PopcornTimeTV/PopcornTimeTV#751]
App version: 3.2.30
tvOS version: 12.1 

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

have the choice to choose subtitle.

#### Actual Behaviour

No subtitle option.

#### Steps to reproduce the behaviour

1. open video
2. display the option
3. no subtitle.

i already read the release not where you describe new feature about subtitle, but no subtitle option is shown and i can't find how to select a subtitle. in the older version, i have multiple languages in the subtitle, nothing in the new one. (if you want test this, you can check with "Venom": old version have subtitle option not the newest, or the with the "Salvation" where i can select the subtitle from "other subtitle" in older version not with the newest).

for now i reinstall the oldest version.

thank you for your effort to keep this app alive :)

**Comment by angryDuck2** [comment]
Would you mind holding off for a couple of seconds after the movie starts playing, before sliding down to reveal the top menu and going to find the subtitles? As I have no issues with Venom. I get a full list of subtitles

**Comment by itshenriqueyall** [comment]
The app crashes every time intro to scroll down to choose a subtitle. I have an Apple TV 4K, anyone knows how to fix it?

**Comment by r1qu3br** [comment]
Try uninstall and install the app again. I solved the problem on my Apple TV 4K :)

**Comment by anonymouse1989** [comment]
The scroll down crash was fixed from the previous update, maybe you installed popcorntime wrongly, try to remove any popcorntime that you have, then reinstall the latest build. Everything works fine for me.

**Comment by r1qu3br** [comment]
> The scroll down crash was fixed from the previous update, maybe you installed popcorntime wrongly, try to remove any popcorntime that you have, then reinstall the latest build. Everything works fine for me.

Here locking also the same way that Itshenriqueyall said, by security I deleted the cache, deleted the app and reinstalled now and the error still persists, when it scrolls down the app crash, use the Apple TV 4K

**Comment by angryDuck2** [comment]
@itshenriqueyall @r1qu3br wrong issue. The original poster has an entirely different issue. Please post a new issue if your problems persist

**Comment by angryDuck2** [comment]
@Red-Mak is this issue still occuring? If not could you please close this issue?

**Comment by Red-Mak** [comment]
Sorry for the delay (i was moving), yes still happen with the last version available even after fresh install and waiting as asked by angryDuck.

**Comment by mrkong8102** [comment]
@Red-Mak  I’m suffering the same issue.  I’m using Apple TV 4K as well. Looks like a bug with 4K and newest app. So what version are you using now? Really need the subtitles.

**Comment by Red-Mak** [comment]
@mrkong8102 i install an older version .. 
i see the issue you  created and i don’t think its because you are in Australia, im in Paris and had the same issue.

**Comment by mrkong8102** [comment]
@Red-Mak That would be not compatible with apple 4k. Hope them can fix it. Do you know what version you installed? A Oder version than 3.2.30?

**Comment by Red-Mak** [comment]
@mrkong8102 the version i use is 3.2.23

**Comment by mrkong8102** [comment]
@Red-Mak will try. Thx mate

**Comment by mrkong8102** [comment]
@Red-Mak my one still not working with my Apple TV. Did I do anything wrong with signing?  Else works fine just subtitles

**Comment by mrkong8102** [comment]
I found the reason.. Australia government blocked open subtitles that’s why I can’t get any subtitles..
