### ISSUE TITLE
Swift 3 - Master

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#97]
When will the master branch be updated to swift 3?

**Comment by tomsbrinkis** [comment]
yea, i still cant update it trough pod.update or install.swift. it just gives me errors. 
:(

**Comment by moh0sw** [comment]
@Hackormahn @FlaviaBondJamesBondsHusband @popcornMaster @tvOSPopcorn 
Yeah the AlamofireXMLRPC error have been fixed but when building the project this making errors

`ObjectMapper`
(“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.)

`AEXML`
(“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.)

`Alamofire`
(“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.)

**Comment by Mr-SMG** [comment]
I still get an AlamofireXMLRPC repo error when trying to compile:

> [!] Error installing AlamofireXMLRPC
> [!] /usr/bin/git clone https://github.com/PopcornTimeTV/AlamofireXMLRPC.git /var/folders/mt/8kfkpfjn1wd5ml_57q3ymgr40000gp/T/d20160929-3555-ephse4 --template= --single-branch --depth 1
> 
> Cloning into '/var/folders/mt/8kfkpfjn1wd5ml_57q3ymgr40000gp/T/d20160929-3555-ephse4'...
> remote: Repository not found.
> fatal: repository 'https://github.com/PopcornTimeTV/AlamofireXMLRPC.git/' not found

**Comment by tomsbrinkis** [comment]
I get this: 

`install.swift:5:18: error: 'NSURLSession' has been renamed to 'URLSession'
public extension NSURLSession {
                 ^~~~~~~~~~~~
                 URLSession
install.swift:10:24: error: 'dispatch_semaphore_t' is unavailable in Swift
        let semaphore: dispatch_semaphore_t = dispatch_semaphore_create(0)
                       ^~~~~~~~~~~~~~~~~~~~
install.swift:11:20: error: 'NSURLSession' has been renamed to 'URLSession'
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {
                   ^~~~~~~~~~~~
                   URLSession
install.swift:25:41: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSURLRequest(URL: url)
                                        ^
                                            as URL
install.swift:31:26: error: 'NSURLSession' has been renamed to 'URLSession'
        guard let data = NSURLSession.requestSynchronousData(request) else {return nil}
                         ^~~~~~~~~~~~
                         URLSession
install.swift:38:47: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSMutableURLRequest(URL:url)
                                              ^
                                                  as URL
install.swift:46:16: error: 'NSTask' has been renamed to 'Process'
    let task = NSTask()
               ^~~~~~
               Process
install.swift:57:20: error: 'NSFileHandle' has been renamed to 'FileHandle'
    let keyboard = NSFileHandle.fileHandleWithStandardInput()
                   ^~~~~~~~~~~~
                   FileHandle
install.swift:65:4: error: missing argument label 'args:' in call
run("-c", "git stash", "git fetch", "git rebase")
   ^
    args: 
install.swift:72:19: error: 'NSURLSession' has been renamed to 'URLSession'
if let jsonData = NSURLSession.requestSynchronousJSONWithURLString("https://api.github.com/repos/PopcornTimeTV/PopcornTimeTV/releases") as? [[String : AnyObject]] {
                  ^~~~~~~~~~~~
                  URLSession
install.swift:86:21: error: missing argument label 'input:' in call
let version = input("Enter the version number: ")
                    ^
                    input: 
install.swift:102:27: error: missing argument label 'input:' in call
let podsInstalled = input("Do you have cocoapods installed? (Enter Yes or No): ").lowercaseString
                          ^
                          input: 
install.swift:105:8: error: missing argument label 'args:' in call
    run("-c", "sudo gem install cocoapods")
       ^
        args: 
install.swift:110:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/.cocoapods/repos/PopcornTimeTV")
   ^
    args: 
install.swift:111:4: error: missing argument label 'args:' in call
run("-c","rm -rf Podfile.lock")
   ^
    args: 
install.swift:112:4: error: missing argument label 'args:' in call
run("-c","pod cache clean --all")
   ^
    args: 
install.swift:113:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*")
   ^
    args: 
install.swift:114:4: error: missing argument label 'args:' in call
run("-c","pod repo remove popcornmaster;pod setup;pod repo update")
   ^
    args: 
install.swift:115:4: error: missing argument label 'args:' in call
run("-c","pod install")
   ^
    args: 
install.swift:116:4: error: missing argument label 'args:' in call
run("-c","pod update")
   ^
    args: 
install.swift:121:4: error: missing argument label 'args:' in call
run("-c", "open PopcornTime.xcworkspace")
   ^
    args: 
Tomss-MacBook:PopcornTimeTV Toms$ `

**Comment by FlaviaBondJamesBondsHusband** [comment]
Install script has been updated as have dependencies however the project itself is yet to be updated to Swift 3. Please note Cocoapods beta version is **VERY MUCH RECOMMENDED** for macOS Sierra and Xcode 8 as earlier versions will give the error @moh0sw is having.

**Comment by chocolatesuper** [comment]
MASTER UPDATE VERSION THANK YOU FRIEND

**Comment by chocolatesuper** [comment]
AND FOR MAC OS X SIERRA SERVES WITH  XCODE 8

**Comment by moh0sw** [comment]
@chocolatesuper do u mean it works with you and build success?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Check out the latest commit to Swift3.0 branch :)

**Comment by bubez81** [comment]
sorry how to use the branch swift 3?

**Comment by Hackormahn** [comment]
@bubez81 download the Swift3.0 branch instead of the master branch.

**Comment by galdo320** [comment]
<img width="1440" alt="screen shot 2016-10-10 at 10 57 00 pm" src="https://cloud.githubusercontent.com/assets/20889281/19257523/450ea538-8f3e-11e6-8352-837e23afb558.png">
finally!!
